### ISSUE TITLE
Completing overview widget for majority of pages

### ISSUE THREAD

**Issue by adamjohnwright** [WormBase/wormbase_rest#110]
I intend on completing the vast majority of Overview widgets. With this ticket I intend on completing the widgets with identical functionality to the catalyst version.

**Comment by adamjohnwright** [comment]
@mgrbyte I am started with the analysis overview widget. And it appears as if the subproject field is missing from the WS258 schema. In the AceDB schema it goes analysis -> group -> [project, subproject]. For some reason the project field exists in the Datomic schema but the subproject does not. 
Any ideas?

**Comment by mgrbyte** [comment]
@a8wright Looking at the ACeDB schema in the [annotated models][1]:
The `?Analysis` class states an `INXREF` from `Group Subproject` to  the `Group Project` tag in the same `?Analysis` class; a recursive self-referential relationship (theoretical unbounded level of sub-projects).

Since the `:analysis/project` attribute is a cardinality-many reference, you'll end up with a set of sets (using the datomic entity API).
```clojure
;; Gets first level of sub-projects. Same logic to called recursively to obtain all, until sub-projects is nil
(let [sub-projects (some->> (:analysis/project entity) 
                        (mapcat :analysis/project)]
  ...)
```
In the annotated modes which drive the  conversion, tags marked with `INXREF` are "dropped" and those marked with `OUTXREF` are kept (this is where the author of the annotated models has chosen a primary direction where a two-way `XREF` exists in the source ACeDB models.

[1]: /WormBase/wormbase-pipeline/wspec/models.wrm.annot

**Comment by adamjohnwright** [comment]
Hi @mgrbyte, thanks for the tap in the right direction. I didn't think that this would be a tree of projects. Which is reasonable base on the tree display on the production website. 

I now feel like I understand what is going on!

I am going with some thing very similar to what you provided:

(if-let [sub-projects (:analysis/_project analysis)]
           (for [sub-project sub-projects]
             (pack-obj sub-project)))

This gives me an array of sub projects. One of which is the one that is listed on the production website. I think the website right now is display just the last sub-project. I am not sure why. 

@sibyl229 do you think it would be right for us to change it to show all sub projects?
