### ISSUE TITLE
Missing In/Sufficient and Un/Neccary evidence on associated anatomy wiget on Phenotype page when pulled from Datomic WS261

### ISSUE THREAD

**Issue by adamjohnwright** [WormBase/wormbase_rest#142]
The table effected is Associated anatomy in the associated anatomy widget: http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000177#17--10

In the Ace version there is Necessary, Unnecessary, Sufficient Insufficient being populated in teh Body Parts fields. but this information is not found in Datomic.

This is the part of the code pulling this information: https://github.com/WormBase/datomic-to-catalyst/blob/develop/src/rest_api/classes/phenotype/widgets/associated_anatomy.clj#L40

As you can see it should be part of the anatomy-function.not-involved holder. But the fields are not present off of these entities.

**Comment by mgrbyte** [comment]
This data is missing because all tags aside from `Remark` in the annotated model's `#Anatomy_function_info`  hash model are marked as `Text` -  but are used as a booleans.

i.e Just setting the tag in ACeDB is considered a boolean operation (data) - the datomic conversion treats this as an empty value since it's expecting a multi-valued string (as per all tags in this hash model are typed as `Text`).

Solution is to remove the `Text` qualifier for all tags other than `Remark` in both the annotated and mailine ACeDB models files.`

We need to check that the `Text` data is not populated/used in the database anywhere.
Once this has been verified, the models can be changed before WS262 conversion begins.

**Comment by Paul-Davis** [comment]
In order to faithfully reproduce the current display this needs to be discussed as both the Remark Text and the qualifier Text is both used so we cannot fix the issue during the conversion. The fix needs to be made at source so this probably needs pushing to WS263?

**Comment by mgrbyte** [comment]
@a8wright This will have to be put back to WS263.
The issue is that in ACeDB, the model defines all the attributes for the `anatomy-function-info` schema as `Text` - which translated to  `[<attr> :db/cardinality :db.cardinality/many :db/type :db.type/string]` attribute in datomic, but the data in ACeDB is valid even if an empty string is specified (just the leaf node is "set").
This means we need to (re-)think the schema design (ACe +/ datomic) for this model.

**Comment by adamjohnwright** [comment]
Thanks for looking into this. WS263 sounds good to me. We maybe should discuss this as a group so that we all are on the same page. For now I have the widgets commented out.

**Comment by adamjohnwright** [comment]
I believe this is now resolved
