### ISSUE TITLE
lineage 500 error

### ISSUE THREAD

**Issue by adamjohnwright** [WormBase/wormbase_rest#151]
I found this in the nginx production log: 

52.23.219.146 - - [12/Dec/2017:12:49:02 +0000] "GET /rest/widget/person/WBPerson635/lineage HTTP/1.1" 500 67 "-" "HTTP-Tiny/0.034"

I just tested it on staging and it caused a gateway timeout 

I think there probably be work done to figure why it is using so much resources.

**Comment by azurebrd** [comment]
Thanks @a8wright .  I'm looking into it, but can't tell how to untangle where to start.

Looking at juancarlos.wormbase widgets worked for other classes, but no widgets worked for person (e.g. overview).  I switched the develop branch and did a 'git pull' and kept getting the same errors.  I tried to stop and restart the datomic-to-catalyst server : lein ring server-headless 4001   but it's getting an error : 
Exception in thread "main" java.lang.RuntimeException: No such namespace: generic, compiling:(rest_api/classes/laboratory/widgets/members.clj:101:1)

I don't know whether something didn't go properly into develop, and that's why it can't start, and I'm confused as to why the person widgets didn't work, but other widgets did.  Do you have some advice on how to get my copy of datomic-to-catalyst to a point that runs so I can branch it and debug this error (which I do see on staging as having other person widgets working).  Thanks !

**Comment by azurebrd** [comment]
@a8wright Oh, I think I see why that's happening.  Will need to patch the laboratory class members.clj  to account for an extra data field when merging my code with your stubs.  There's still another error past that though : 

Started nREPL server on port 41460
Exception in thread "main" java.net.BindException: Address already in use, compiling:(/tmp/form-init3015458591603639907.clj:1:73)

I have no idea about that.

**Comment by azurebrd** [comment]
@a8wright Found the problem.  I can start debugging it now.  Thanks for merging the other bit with members.clj

**Comment by mgrbyte** [comment]
Likely cause is the use of `*` in pull expressions [here][1], [here][2] and [here][3].

This will select _all_ attributes in the relation(s); better to only pull the attributes that are needed.
The attributes select should include just those needed by the `:where` clause of the query, and the `generate-map` function (since the result of these queries are fed into that function).

Rationale for the above hypothesis is that using [wildcarding][5] in datomic pull expressions will pull all component attributes recursively, and `supervised-by` relation of a person is such an attribute (schema marked up with `:db/isComponent`). 
It's recommended only to use wildcarding when you're sure that the set of fields to be consumed are small (and not component attributes/entities)

[1]: https://github.com/WormBase/datomic-to-catalyst/blob/9d55d7d4ef58fb1a2eee78e812cf42bd48899274/src/rest_api/classes/person/widgets/lineage.clj#L43
[2]: https://github.com/WormBase/datomic-to-catalyst/blob/9d55d7d4ef58fb1a2eee78e812cf42bd48899274/src/rest_api/classes/person/widgets/lineage.clj#L59
[3]: https://github.com/WormBase/datomic-to-catalyst/blob/9d55d7d4ef58fb1a2eee78e812cf42bd48899274/src/rest_api/classes/person/widgets/lineage.clj#L75
[5]: http://docs.datomic.com/pull.html#wildcard-specifications

**Comment by adamjohnwright** [comment]
@acabunoc @mgrbyte last night I started a hotfix branch to fix this widget. So far I have taken out all datomic queries. I think I need one more night.

@mgrbyte Thanks for looking at this. I also thought that it was likely the queries that were causing the issue. I am also trying to detangle all the  logic in order to make the code more strait forward. By doing so, I am trying to make sure there isn't anything else.

@azurebrd after I am done making the changes, it would be good for you to go through my changes and try to change our other widgets to the same style.

**Comment by azurebrd** [comment]
@a8wright Thanks Adam, sorry about the trouble.

@mgrbyte Thanks Matt, I didn't know how to query into that directly, and doing that pull * extracted data into a json structure that I could extract from.  Didn't realize it would recursively travel all around.  I checked Bob Horvitz and Sydney Brenner, who have a huge number of nodes and they came out okay before, but now they're not loading.  

@a8wright Thanks Adam, I appreciate you figuring out a better way to do things, and I can follow the patterns to change the laboratory members.clj, which is the only other widget I've written that uses a pull * like that.

**Comment by adamjohnwright** [comment]
@azurebrd I think I also wrote an email to you but, no trouble at all really. It was a fair bit of work but it is a really hard part of the website. There are definitely some difficult technical challenges to this problem. I actually enjoyed having the chance to make json, turn it into a string, and then inject it into json. Kinda funny but it works. Also, I would not have been able to make the changes I made without starting from your code. Also, I don't think that what I wrote is perfect by any means. I think it works but it probably could be refactored again to become even more efficient / elegant. Let me know if you need any help with adjusting the recursive and scaling functionality.

**Comment by azurebrd** [comment]
Resolved with recent fixes with Adam
