### ISSUE TITLE
Code re-organisation

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/wormbase_rest#43]
## Proposed new folder + file structure 
(also merged get_handler.clj and rest/core.clj into core.clj)

@a8wright, @sibyl229 - as discussed on today's call, this is what I think would be a good start.
Any thoughts/objections on the suggestion below?
 
If in agreement, will leave actually doing this until you've merged active branches into develop :)
```
└── datomic_rest_api
    ├── core.clj
    ├── edn.clj
    ├── fields
    │   └── gene.clj
    ├── interactions.clj
    ├── locatable_api.clj
    ├── object.clj
    ├── references.clj
    ├── utils
    │   ├── date.clj
    │   └── db.clj
    └── widgets
        └── gene.clj
```

`edn.clj` should be moved out of this project to pseudoace/common wormbase library.

**Comment by sibyl229** [comment]
Hi @mgrbyte I like the idea of removing `rest/` directory and promote its sub-directories one level up.
Merging changes after current branches are merged in is great. Thank you!

In terms of the files originally reside in `rest/helpers/`, I wonder if they might need a containing directory, because as more of them are added, they probably would obscure the folder structure of `datomic_rest_api`.
