### ISSUE TITLE
Section of JSON should be called fields

### ISSUE THREAD

**Issue by adamjohnwright** [WormBase/wormbase_rest#61]
Here is an example section from the top of the json returned:

{
  "name" : "WBGene00000001",
  "class" : "gene",
  "url" : "/gene/WBGene00000001/sequences",
  "sequences" : {
    "name" : {
      "data" : {
        "id" : "WBGene00000001",
        "label" : "aap-1",

This should be:

{
  "name" : "WBGene00000001",
  "class" : "gene",
  "url" : "/gene/WBGene00000001/sequences",
  "fields" : {
    "name" : {
      "data" : {
        "id" : "WBGene00000001",
        "label" : "aap-1",

*in all the widget URIs that are generated this should be fields. The fields is not present in the field URIs. A similar check should be made for these URLs as well.

**Comment by sibyl229** [comment]
Hi @mgrbyte just to clarify, the `/rest/widget/` and `/rest/field/` urls is expected to produce slightly different data structure. 

The former:
```
{
"name" : "WBGene00000001",
"class" : "gene",
"url" : "/rest/widget/gene/WBGene00000001/sequences",
"fields" : {
  "FIELD_NAME1" :...
}
}
```

The latter:
```
{
"name" : "WBGene00000001",
"class" : "gene",
"url" : "/rest/field/gene/WBGene00000001/FIELD_NAME",
"FIELD_NAME" : ...
}
```

The url in the JSON also needs changing: the /rest/(widget|field)/ prefix was missing.

Thanks a lot @mgrbyte

**Comment by mgrbyte** [comment]
I've noticed in both examples given above, you're referring to `url` in the response, but I think it _should_ be `uri` (if the `download` feature on the website's widget is what we are comparing against).

**Comment by mgrbyte** [comment]
For independent fields (e.g `fkpm_expression_summary_ls` and `alleles_other`), http://staging.wormbase.org/rest/field/gene/WBGene00000421/alles_other?content-type=application/json produces a uri with a prefix of `/species` (instead of `/rest/gene` as I would of expected) - is this correct?

**Comment by sibyl229** [comment]
Hi Matt,

It should be rest/field, as in the url endpoint.

Thanks,

Sibyl

**Comment by mgrbyte** [comment]
@sibyl229 @a8wright I've been adding tests for the routing code, and will update #64 in due course.

In the meantime, I've across another potential issue:
Currently, the routing code publishes all (gene) widget fields under the URI prefix `/rest/field/gene/` -
and each response contains:

`{:name "gene" :uri "/rest/field/gene/<id>/<field-name>" :<field-name> <data>}`
 
This is an issue when `<field-name>` is the `name` field, since it overrides the `name` field at the top-level which is intended to be `"gene"`.
We can either make a special case in the code for not publishing the `name` field, turn off publication of all gene widget fields by default or something else.
