### ISSUE TITLE
person/overview address lines out of order

### ISSUE THREAD

**Issue by adamjohnwright** [WormBase/wormbase_rest#93]
The order of the lines being produced by d-t-c is out of order. I don't know if Clojure is just receiving them out of order or if there is a cause in the code but this should be fixed 

example:

 http://staging.wormbase.org/resources/person/WBPerson30813#01--10
vs. 
http://www.wormbase.org/resources/person/WBPerson30813#01--10

**Comment by azurebrd** [comment]
From https://wormbase-db-dev.slack.com/messages/general/

Adam noticed that the street address information of Person objects isn't ordered correctly.  The ACeDB data is ordered in the order it's written in.  In postgreSQL we have an explicit order column, but dump to ACeDB without any order labeling, just in the correct order, and ACeDB queries it out in the same order it was entered.   Does anyone know if the ACeDB -> Datomic transfer keeps the data in order ?  If it doesn't, we need to alter the population to keep the correct ordering of all #Address.  Or alter the schema to store it differently, like Paper->Author, which uses :ordered/index.  Or alter the ACeDB schema to use LongText and dump it as a single paragraph.

As far as I can tell from looking on Down with this query
[:find ?col1-id (pull ?col2 [*]) ?col3 :in $ ?log :where [?col1 :person/id ?col1-id] [(ground "WBPerson30813") ?col1-id] [?col1 :person/address ?col2] [?col2 :address/street-address ?col3]]
:address/street-address is a vector sorted alphanumerically (small sample size, tried a few
people, but it gives : numbers, uppercase letters, lowercase letters), but possibly the (p
ull [*]) sorts it that way, and the data isn't sorted that way ?
The col3 street address data from the query is in a different order as the col2 data, but i
t seems random, as it's also not correct.

If the data is ordered correctly, could someone tell me the way to query it in the correct order ?

**Comment by adamjohnwright** [comment]
I believe @mgrbyte said that he would take a look. If he does not I can take a look tomorrow.

**Comment by azurebrd** [comment]
Cool, thanks @a8wright

**Comment by mgrbyte** [comment]
@a8wright @azurebrd 
The links in the OP seem to show identical content.
Furthermore, the staging site seems indicate that the data is coming from ACeDB, not datomic as I was expecting -perhaps staging has been updated in the meanwhile?

**Comment by mgrbyte** [comment]
@azurebrd @a8wright @sibyl229 
The schema for `:person/street-address` is automatically inferred as follows by the [model conversion code][1] in pseudoace:
```
{:db/ident :address/street-address,
 :db/valueType :db.type/string,
 :db/cardinality :db.cardinality/many,
 :db/index false,
 :pace/tags "Street_address"}
```

* This is schema is automatically translated from the ACeDB models - there is no explicit reference anywhere in the pseudoace (model conversion code) that mentions address.

 * `:ref` `:many` attributes in datomic are realised as sets:
    ```clojure
    (def p1 (d/entity db [:person/id "WBPerson21947"]))
    (def sa (:address/street-address (:person/address p1)))
    (println (type sa) sa)
   ```
   Outputs:
  ```
   clojure.lang.PersistentHashSet #{"Wellcome Trust Genome Campus" "Parasite Genomics" "Hinxton, Cambridge CB10 1HH" "Wellcome Trust Sanger Institute"}
  ``` 

The ACeDB schema has:
```
#Address  Street_address Text           // multiple lines including town, state, zip/postcode, whatever 
````

As described above,  the attribute `:address/street-address`  is inferred mapped to  a schema having: 
  *  `:db/valueType :db.type/string` (mapped from the `Text` type in ACeDB model)
  * `:db/cardinality :db.cardinality/many` (due to lack of UNIQUE tag in ACeDB model)

The result is that it's (effectively) being stored as a set when used with datomic APIs (`entity`, `pull` ,  `datoms`) , and the original ordering is lost.

A potential solution is to change the source ACeDB annotated models to:
```
#Address Street_address UNIQUE Text
```
which I believe would preserve the ordering, but that might have ramifications.

@Paul-Davis any thoughts?

[1]: /WormBase/pseudoace/blob/master/src/pseudoace/model2schema.clj#L109-L323

**Comment by khowe** [comment]
I recall Thomas coming across this issue with Author lists for papers, and putting a solution in place.

**Comment by mgrbyte** [comment]
@khowe Perhaps you're recalling work he did on an [earlier prototype][1]:

> Authors tags in papers are in alphabetical order, not as listed in the publication. Appears to be no way of reconstructing actual authorship order (FIXED)

where  the schema was [modelled][2] directly using EDN (datomic). 

AFAICT, the solution he used there cannot apply to the automated conversion of the `model.wrm.annot` file as done in pseudoace.

[1]: /WormBase/db-prototypes/blob/780aa17bedd93999d2024520d5b5971a2a11ee85/platforms/datomic/README.md
[2]: /WormBase/db-prototypes/blob/780aa17bedd93999d2024520d5b5971a2a11ee85/platforms/datomic/schema.edn

**Comment by azurebrd** [comment]
@a8wright @azurebrd I don't know why staging is serving ACeDB data, but you can see the Datomic data here http://juancarlos.wormbase.org/resources/person/WBPerson30813#01--10

@mgrbyte Where are you entering the commands (def p1 (d/entity db [:person/id "WBPerson21947"])) and so on ?  It was nice to have a lein repl to directly query Datomic, but we haven't had that for a while.  I think Down is limited to [:find] queries, but please let me know if that's not the case, or there's a way to access Datomic directly. 

@mgrbyte @khowe @Paul-Davis As far as I know, Street Address and Paper-Author are the only cases in WS where the order of data matters, but I hadn't thought about Street Address before, so there may be other cases where it matters.  The Street Address data has multiple lines, which is why I suggested a LongText model change instead of UNIQUE Text.  We could store it as UNIQUE Text if the data had linebreak delimiters.  Sometimes in postgreSQL we use | separation to split separate text lines/objects in a single database entry, and split while dumping the .ace for upload.  This would add an extra step on the webpage display query, but it's probably not a big deal.  It makes the data less clean, which might be a bigger deal.  I don't know how the mapping of Paper-Authors happens now, but I think the resulting structure in Datomic uses :ordered/index

**Comment by adamjohnwright** [comment]
I have fixed staging. There was a change to how we are working with docker in the makefile. everything is good now.

**Comment by azurebrd** [comment]
Cecilia says that having separate street address lines in separate fields is useful to her, because the autocomplete for curating it helps keep the same lines the same across different Persons, and allows entering other lines individually (like Mail Codes being different in one line, while street number and street name is the same).  We could still change it in ACeDB to a single field and keep it in postgreSQL as separate ordered fields, but probably best if Datomic could be populated with the data in order.  Alternatively, we could populate person data in Datomic from postgreSQL, bypassing ACeDB, if that lets us enter the data in order.

**Comment by mgrbyte** [comment]
@azurebrd 
As I show In my last comment above, `Street_address` is already a single field in the ACeDB models:
```
#Address  Street_address Text 
```
This translates to a datomic attribute schema with:
```
   :db/valueType :db.type/string
   :db/cardinality :db.cardinality/many
```
with the semantics as afore-described.

There 87 other such schema attributes having the same translation, where order may (or may not) be significant.

A way to see these occurrences is:

```bash
# assume you've git clone'd the pseudoace repository to ~/git/pseudoace 
cd ~/git/psuedoace
# ensure you're looking at the latest.
git checkout master
git pull
# find all schema attributes that result in a cardinality-many string type: 
grep -r ":string :many" ~/git/pseudoace/generated-schemas/schema258.edn
````

### options
As far as I can see, the options for populating the address field in-order are:
 1. write in a special case(s) in the importer code
 2. change the source ACeDB models to add `UNIQUE` to the attribute definition, where appropriate.

### solutions
(1.) is the error prone and tricky to implement (how many special cases to do we need to add?)
      divergence of the ACeDB representation from that in datomic (most other cases have a 1-to-1 translation rule, this would break that invariant)

Therefore, (2.) is my preference, should it be possible.

Should (2.) not be possible for any reason, then (1.) would take substantial effort/time, and this would not be available until at least WS259.

**Comment by azurebrd** [comment]
Thanks @mgrbyte.  I realize it's a lot of work and not a good thing to start writing in exceptions.  I don't think it matters much in terms of timeline, I think the models freeze for WS259 already happened, so the change couldn't happen until WS260 if we went route (2).  This is probably more of a test case to figure out what we're trying to do in terms of curation database vs release/website database, and in terms of curator involvement with modeling.  Having the separate street lines be separate entries in the curation database is preferred by the curator for the autocomplete fields.  If we separate curation DB from release DB, this isn't an issue, so long as the data can be displayed properly.  For more complicated model changes, Caltech curators of biological data would possibly have a bigger interest in being involved.

**Comment by azurebrd** [comment]
LongText in ACeDB wouldn't work, it's in an #Address hash, so there's no way to reference the hash object.  (Please correct me if that's not true).  To put it all in one line, we'd need to enter artificial delimiters and split on them for web display.  This seems like a non-ideal database practice, so I think we should discuss it more.

**Comment by azurebrd** [comment]
A slight correction on the grep, since some fields have other attributes between :string and :many 
grep -r ":string" schema257.edn | grep ":many"

Combining the attributes Matt mentioned with the direct server queries Sibyl mentioned elsewhere, this query 
[:find ?ident
 :where
 [?e :db/ident ?ident]
 [_ :db.install/attribute ?e]
 [?e :db/valueType :db.type/string]
 [?e :db/cardinality :db.cardinality/many]
]
works on 
  http://datomic-rest-dev.wormbase.org:8888/browse
albeit returning 195 values, as opposed to 192 from a grep on the schema file.

**Comment by mgrbyte** [comment]
@azurebrd Yes, the reason for the discrepancy between the grep on the schema file and datalog query is the later will be also including "system" attributes in datomic (attributes that have the namespace "db")

**Comment by azurebrd** [comment]
Cool, thanks @mgrbyte 

Would it work as a solution in the automated ACeDB -> Datomic mappings, to change the ACeDB #Address model to 
#Address Street_address Int Text 
from the current
#Address Street_address Text
and use that Int field as an explicit ordering index ?  If it does, would we want that as a general solution for any ACeDB ordered fields ?

I don't know if there's an exception for handling the ordering of Authors in the ACeDB -> Datomic mappings, but if there is, would we then be able to deprecate that by changing the ?Paper model's Author line to 
Author Int ?Author XREF Paper #Affiliation
@khowe I don't know whether the latter makes sense because of the XREF back to Paper.
If that doesn't work, could we / would we want to tack on an Author_order field into the #Affiliation hash ?  It's not what it's for, but it could hold the data, possibly rename it #Author_info

**Comment by mgrbyte** [comment]
@azurebrd I discussed this issue with @khowe today, and we came across a solution that Thomas has already put in place for other attributes that are cardinality-many, where we want to preserve order.

Here's an example of this being used in the [annotated][2] models to keep the list of authors for a paper ordered.

Making this change to will result in the datomic type of the `street-address` attribute to be `:db/valueType :db.valueType/ref`, which will a corresponding `ordered` component. 

The entity map for street-address will then have an [index][1] attribute you can use for ordering. 

I'll test this out for street-address, and if it works fine will put the changes in for WS259.

I think you'd then be able to do something like:
```clojure
(sort-by :ordered/index (:address/street-address person))
```

[1]: /WormBase/pseudoace/blob/master/generated-schemas/schema258.edn#L181
[2]: /WormBase/wormbase-pipeline/blob/master/wspec/models.wrm.annot#L3296

**Comment by azurebrd** [comment]
Cool cool, thanks @mgrbyte !

**Comment by raymond91125** [comment]
Apologies if I have not comprehended the background sufficiently to comment. But, that never stopped me before. 8-)

@azurebrd Wouldn't any field that benefits most from auto complete have an implicit type? That is, you would want to auto complete on Town, State, Postal code independently rather than mixed altogether. If so, they could/should be segregated into different fields. 

More generally, perhaps we could make use of a relationship tag for ordering, e.g. "[immediately preceded by](http://purl.obolibrary.org/obo/RO_0002087)". We will be adding this relationship in ?life_stage class (to replace Preceded_by).

**Comment by mgrbyte** [comment]
@raymond91125 I discussed this at length with @Paul-Davis, and we came to the same conclusion (this street address field would be _ideally_ decomposed into separate attributes/tags)
I'm not sure how much work this would be change in both the curation web-forms system at CIT, and in the website code.

This #Ordered hack has some potential technical drawbacks.

**Comment by azurebrd** [comment]
@raymond91125 @mgrbyte 
In ACeDB the data is not well tokenized, and it would be good to split it up more
?Address	Street_address	Text
	Country	UNIQUE	Text
	Institution	Text
	Email	Text
	Main_phone	Text
	Lab_phone	Text
	Office_phone	Text
	Other_phone	Text	UNIQUE	Text
	Fax	Text
	Web_page	Text

In postgres
http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/person.cgi
We split up Street_address into 
Institution 
Street
City 	
State 	
City postal code 	
Country

The bigger problem is that the Street field itself needs to be split up into separate fields, and I think they're not easily split, nor maybe even always ordered the same across different addresses.  Possible lines being : 
257 South 1400 East
Cambridgeshire CB10 1RQ
Hinxton Hall
The Sanger Centre
Laboratoire d'Oncologie Moleculaire
Departments of Pediatrics, Cell Biology
PO Box 511
Box 0448
Beckman Center, B300
Mail Stop: NB302 

It might be clear to Cecilia how many different types of fields we could have, but it's not clear to me, and I'm pretty sure it wouldn't be straightforward to find clear field labels for users to understand what to enter into each field when updating their data.  Also, if we can't always construct an address in the right order because the fields might be ordered differently in different countries or what-not, we'd need to find the proper rules and program them.  

Even if we could do all that, it would be a lot of work to go back for the 37000+ people and retokenize their address information (and old-address information).  So we'd still an ordered field in the database for the period it takes to update that.

I agree that at least splitting Street_address into Street, City, State, City, postal code, Country is a good thing.  But we'll still have the ordering issue for the multivalue Street field.

**Comment by azurebrd** [comment]
@raymond91125 How does "immediately preceded by" work ?  The street line "The Sanger Centre" is immediately preceded by "Hinxton Hall" ?

**Comment by raymond91125** [comment]
@azurebrd Yes, retrofitting would be time consuming. Another thought is that some disambiguation and consistency may be helped by separating Street address from On-campus address.

Your usage of "immediately preceded by" is what I have in mind. It will need the construct like:
Address "The Sanger Center" Immediately_preceded_by "Hinxton Hall"
Address "Room 232" Immediately_preceded_by "The Sanger Center"

**Comment by azurebrd** [comment]
@raymond91125 Ah, that's a good idea.  In that case I still think it would be better to just number the lines, making the model Street Int Text.
